### ISSUE TITLE
Can I use it, should I try it?

### ISSUE THREAD

**Issue by piegamesde** [idanarye/woab#1]
Hi, what's the state of this project? Is it more like some idea or research prototype, or is this something that I can actually take and build my application upon? Has this already been used somewhere except for the examples?

**Comment by idanarye** [comment]
It is read for usage - it's just not battle tested. I'm using it in two projects (https://github.com/idanarye/kosem and https://github.com/idanarye/chapter-tracker/tree/rs-sqlx) but these projects are so undercooked I couldn't really list them as usage examples.

That being said - as far as GUI frameworks go (and if you squint hard enough you can call WoAB a GUI framework) WoAB's scope is extremely limited. The GUI is GTK. Not based on GTK (like Relm) - it **is** GTK. I'm not creating my own components and signals - all I do is:

* Map the components from Glade files to Rust structs.
* Route the signals from these Glade files to Tokio streams and attach these streams to Actix stream handlers.
* Provide a way for the Tokio reactor (which Actix runs on) and the GTK event loop to run together, in the same thread.

So, with the scope being so small, even thought the codebase and feature list are small I consider them production ready and see nothing obvious to add to them. Of course, if you do decide to try it for your project you may encounter features that WoAB should - and if it's within the scope of WoAB I'm always open to bug tickets and pull requests.

**Comment by piegamesde** [comment]
Great, thank you. I already gave it a try, expect me to come back with issues and feature request :)

> WoAB's scope is extremely limited

That's what I like so much about it. I can pretty much reuse all my existing code and the migration path is pretty good. All parts are optional: at the moment, I copied the code that registers event handlers into the `started` method and it works. I can go ahead and use the signals bridging later on. I also like that I can just choose which parts to use and which not. (For example I didn't understand the `Factories` macro and it doesn't seem to do what I needed so I simply went without.)

**Comment by idanarye** [comment]
Since I'm using Glade and builders, WoAB is pretty much geared toward using `Factories`. Is there anything I should add to help your builder-less usecase?

**Comment by piegamesde** [comment]
At the moment no, I don't even know what I want/need ^^. I'll create new issues once I'm ready. I'm just messing around a bit, figuring out patterns that work well. For example I currently use `woab::BuilderUtilizer::from(builder.clone()).actor(…)` to instantiate all my actors manually from the same Builder. This works rather well with the exception that only the first one will get all the signals.

**Comment by idanarye** [comment]
That's because the factories are running the builder from the XML every time to create multiple builders, each with their own signals.

What are you finding hard to understand with the factories? Maybe my documentation is lacking and all it takes is to fix that...

**Comment by piegamesde** [comment]
I've factored out my problem into #3. Regarding the documentation, I think my problem is not with the concept of the factories struct, but rather the `Factories` derive macro. Why does it take one XML file and how does it dispatch that XML to the `BuilderUtilizer`s? I've had a glance at the code and it seems to do some parsing?
