### ISSUE TITLE
Disable "resolver" feature in actix

### ISSUE THREAD

**Issue by piegamesde** [idanarye/woab#16]
Also, maybe have a look at other dependencies and which default features they bring that are not necessary.

**Comment by idanarye** [comment]
Actix 0.11 no longer has `resolver` as a default feature, but it does have `macros` which WoAB is not using.

The only other dependency that has default features is hashbrown, with
```toml
default = ["ahash", "inline-more"]
```

`ahash` is the hashing algorithm, which is needed. `inline-more` is described as:
> Adds inline hints to most functions, improving run-time performance at the cost of compilation time. (enabled by default)

So I think I'll keep it.

**Comment by idanarye** [comment]
Closed by https://github.com/idanarye/woab/commit/f31b2965b7b6895634e2ad492ad1c42c788699a1. Forgot to use the commit message magic...
