### ISSUE TITLE
How to add glib sources?

### ISSUE THREAD

**Issue by piegamesde** [idanarye/woab#18]
Say I want to connect some closure to [`timeout_add_local`](https://gtk-rs.org/docs/glib/source/fn.timeout_add_local.html) or the like, what's the best way to do this? I guess at the moment I'll have to clone the `Addr` and then send the event from there, but maybe a Woab-native solution would be preferable. Especially because the `Continue` return value has very similar problem characteristics to our `Inhibit` problem.

**Comment by idanarye** [comment]
Why do you need to involve GTK? Why not do this from Tokio/Actix? Just launch a future that sends the message you want in a loop. Instead of returning `Continue`, just terminate the loop.

**Comment by piegamesde** [comment]
That's a very good point, I never thought about this. However, there are a few other methods in [that module](https://gtk-rs.org/docs/glib/source/index.html), and I don't know how accessible alternative implementations are.

In my case, I'll indeed try out what you suggested, but this will probably come up again the day somebody wants to use one of these other methods (if that ever happens ^^).

I'm closing this for now as the implementation cost are probably higher than the workaround cost.

**Comment by idanarye** [comment]
The main problem here is how to crank the Tokio loop from inside the handler, which I'll already need to solve for #19. I'll just have to expose that ability to the user - something like:

```rust
glib::source::timeout_add_local(100, move || {
    let future = addr.send(TickMessage);
    let result = woab::block_on(future);
    glib::source::Continue(result)
});
```

**Comment by idanarye** [comment]
I updated Tokio and Actix, and it turns out I had to implement [`woab::block_on`](https://idanarye.github.io/woab/woab/fn.block_on.html) in order to get anything at all to work. Try it out and see if it works for your usecase.
